MyName = "NAD";
MyHP = 667;
MyMaxHP = 667;
CheckDescription[0] = "* NAD - 10 ATK 67 DEF *"
CheckDescription[2] = "* C'est mon but ultime de rentré&à cette école et je vais TOUT&donner pour y arrivé."
CheckDescription[3] = "* Je ne suis pas obligé&d'utiliser la force *"
CheckDescription[1] = "Un leader reconnu dans le domaine&de la créativité numérique au&Canada."
Act[0] = "Inspecter";
Act[1] = "Passion";
Act[2] = "Création";
Act[3] = "Modélisation 3D";
PeaceText[0] = "*Je ne peux pas& ~RATTAQUER ~Dmon école!!!*"
PeaceText[1] = "Autre chemin"
ShowHealthBar = true;
CanSpare = true;

Killed = false
Attack = 4;
Defense = 0;
Dialogue = noone;
ReadyForBattle = false;
PressFight = noone;
Taunted = false;